### ISSUE TITLE
Unicode app names can cause problems with Castle's headers

### ISSUE THREAD

**Issue by dlew** [castle/castle-android#29]
In Trello, if you turn on [pseudolocalization](https://developer.android.com/guide/topics/resources/pseudolocales), it will mess with the app's name. As a result, Castle's SDK will blow up when it tries to insert it into an OkHttp header:

```
Unexpected char 0x162 at 1 in User-Agent value: [Ţŕéļļö one two]/2020.5.13837-production (13837) (motorola Moto G (4); Android 7.0; Castle 1.1.2)
okhttp3.Headers$Companion.checkValue
```

We're going to disable pseudolocalization of the app name anyways, but it might also be worth sanitizing the input to the headers to avoid illegal characters.

**Comment by sebastiansimson** [comment]
Thank you for reporting this, I have created a fix for this that will be included in the next release.

**Comment by dlew** [comment]
Just saw another case recently - I think the updated code should handle it, but if you want to be 100% safe you should check this (since the invalid character comes from the device, not from the app):

```
Unexpected char 0xb2 at 55 in User-Agent value: Trello/2020.6.13953-production (13953) (motorola Moto Z² FORCE; Android 8.0.0; Castle 1.1.4)
okhttp3.Headers$Companion.checkValue
```

**Comment by sebastiansimson** [comment]
Thank you for letting us know about this case as well. I have verified that the fix handles this case as well.
