### ISSUE TITLE
(v2.1.0) Do clients need to care about Castle::requestTokenHeaderName?

### ISSUE THREAD

**Issue by stkent** [castle/castle-android#44]
In #43, the method `Castle::clientId` was deprecated in favor of `Castle::createRequestToken`. Alongside this change, a new constant, `Castle::requestTokenHeaderName` was [added](https://github.com/castle/castle-android/pull/43/commits/9cd4f976a12be78bb3c99b25d0422018145ed858), then [updated](https://github.com/castle/castle-android/pull/43/commits/1887f66f77472e266068bcc8feca898c6d9bc15a), then [removed](https://github.com/castle/castle-android/pull/43/commits/49f42d5e7318936f78fef498f2621e2bd8349392), then [added](https://github.com/castle/castle-android/pull/43/commits/b9eb5d3d19a4e7d92424420a3e6745095d9888d4) again.

In updating our current code to use v2.1.0 of the Castle SDK, I've been replacing usages of the deprecated method `Castle::clientId` with the new method `Castle::createRequestToken`, but have _not_ been replacing usages of the (not deprecated) constant `Castle::clientIdHeaderName` with the new constant `Castle::requestTokenHeaderName`.

Is this migration strategy correct? As users of the Android SDK, do we need to care (or will we eventually need to care) about the `Castle::requestTokenHeaderName` constant?

**Comment by sebastiansimson** [comment]
What you describe is a correct way for v2.1.0. The constant `Castle::clientIdHeaderName` will eventually be replaced with `Castle::requestTokenHeaderName` and deprecated with a future api update.

So you don't have to care about it now but will need to migrate to using `Castle::requestTokenHeaderName` in a future release.

Sorry about the confusion around this
