### ISSUE TITLE
NullPointerException while configuring sdk

### ISSUE THREAD

**Issue by Th4n** [castle/castle-android#68]
Hey, 

We are seeing some users running into the following crash (around 40 users with 900 crashes last 3 months) on a pretty big app:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
       at io.castle.highwind.android.f.a(:818)
       at io.castle.highwind.android.s.g(SourceFile:1)
       at io.castle.highwind.android.Highwind.token(:2)
       at io.castle.android.Castle.n(SourceFile:1)
       at io.castle.android.Castle.e(SourceFile:1)
       at io.castle.android.api.model.Event.<init>(:11)
       at io.castle.android.api.model.CustomEvent.<init>(SourceFile:2)
       at io.castle.android.api.model.CustomEvent.<init>(SourceFile:1)
       at io.castle.android.Castle.f(SourceFile:1)
       at io.castle.android.Castle.q(SourceFile:1)
       at io.castle.android.Castle.d(SourceFile:1)

       from:  Castle.configure(application, apiKey)
```
I'm not exactly sure how to reproduce the issue, but it seems like most people are using Samsung devices (50%), and Android 10 (62%) (whereas Android 12 is (37%), and Android 11 (<1%) on minSdk=24). Moreover, according to Firebase around 75% of those users are in background, and the issue is marked as "early crash" meaning: `96% of crash events for this issue happened in the first 5 seconds of a user's session`

We're initializing sdk inside a coroutine and I was wondering whether that's something we shouldn't be doing, or is there some internal issue underneath.

**Comment by sebastiansimson** [comment]
Hi and thank you for reporting this.

The SDK is not fully tested being initialized in a coroutine but it should work. Based on the numbers you provided it looks more like something is going wrong internally on certain Android versions.

What version of the Castle SDK are you using?

I will investigate a bit more and get back to you later today

**Comment by sebastiansimson** [comment]
Also, is the stacktrace you provided obfuscated? If so, are you able to provide a retraced version?

**Comment by Th4n** [comment]
It's the newest one 3.0.7. Unfortunately, yes it is obfuscated (due to reasons) and I'm not exactly sure if I'll be capable of retrieving the mapping file, but I'll try to do my best.

**Comment by sebastiansimson** [comment]
Thank you for the retraced stacktrace

It seems to be an issue with the obfuscation of the library that produces invalid code handling a variable that can is nullable as non-nullable and therefore resulting in this exception.

We are testing a fix and will update the SDK after that, will update the issue when that is done.

Thanks again for reporting this
