### ISSUE TITLE
Getting Failed to resolve: com.squareup.tape2:tape:2.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by shercoder** [castle/castle-android#9]
After adding `api 'io.castle.android:castle:1.0.2'` or `compile 'io.castle.android:castle:1.0.2'` to our android project, I'm getting the following error when I attempt to sync with gradle:
`Failed to resolve: com.squareup.tape2:tape:2.0.0-SNAPSHOT`

minSDKVersion: 21
compileSDKVersion: 27
targetSDKVersion: 26
React Native version: 0.57.2

**Comment by sebastiansimson** [comment]
The 1.0.2 release uses Tape2 which at the time of release was only available in the Sonatype snapshit repository. Add the following maven repository to your `build.gradle`

```
maven {
	url "https://oss.sonatype.org/content/repositories/snapshots"
}
```

This requirement will be removed in the next release.
